version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    assignees:
      - scaramangado
    target-branch: develop
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    assignees:
      - scaramangado
    target-branch: develop
