lily:
  commandline:
    enabled: false
  discord:
    enabled: true

ootbingo:
  jobs:
    srl-sync:
      enabled: true
      cron: 0 30 0 * * ?
    racetime-sync:
      enabled: true
      cron: 0 30 1-23 * * ?

gg:
  racetime:
    enable-racing: false
    api:
      data-base-url: https://racetime.gg

spring:
  datasource:
    url: jdbc:postgresql://scaramangado.de:10010/BARINADE
    driverClassName: org.postgresql.Driver
    username: scaramanga
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
