lily:
  commandline:
    enabled: false
  discord:
    enable-direct-messages: true

ootbingo:
  races:
    blacklist:
      - 219509
      - 100176
      - 67638
      - 91357
      - 86393
      - 108069
      - 90718
      - 128327
      - 176483
      - 18042
      - 17667
      - 18680
      - 15910
    whitelist:
      - raceId: 264444
        goal: https://ootbingo.github.io/bingo/v9.4/bingo.html?seed=848930&mode=normal

com:
  speedrunslive:
    api:
      base-url: https://api.speedrunslive.com

gg:
  racetime:
    enable-racing: true
    api:
      data-base-url: http://localhost:8000
      racing-base-url: http://localhost:8000
      websocket-base-url: ws://localhost:8000
      oauth:
        client-id:
        client-secret:

bingosync:
  base-url: http://localhost

logging:
  file:
    name: bot.log
    max-history: 15

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:flyway/prod
