lily:
  commandline:
    enabled: false

ootbingo:
  races:
    blacklist:
      - 219509
      - 100176
      - 67638
      - 91357
      - 86393
      - 108069
      - 90718
      - 128327
      - 176483
      - 18042
      - 17667
      - 18680
      - 15910
    whitelist:
      - raceId: 264444
        goal: https://ootbingo.github.io/bingo/v9.4/bingo.html?seed=848930&mode=normal



com:
  speedrunslive:
    api:
      base-url: https://api.speedrunslive.com

gg:
  racetime:
    api:
      base-url: https://racetime.gg
