lily:
  commandline:
    enabled: false
  discord:
    enabled: true

ootbingo:
  jobs:
    srl-sync:
      enabled: true
      cron: 0 30 0 * * ?
    racetime-sync:
      enabled: true
      cron: 0 30 1-23 * * ?

gg:
  racetime:
    enable-racing: false
    api:
      data-base-url: https://racetime.gg

bingosync:
  base-url: https://bingosync.com

spring:
  datasource:
    url: jdbc:postgresql://scaramangado.de:10010/BARINADE
    username: scaramanga
