lily:
  commandline:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  main:
      banner-mode: "off"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

logging:
  file:
    name:
  level:
    root: OFF
    org:
      springframework: OFF
    ootbingo: DEBUG
