lily:
  commandline:
    enabled: false
  discord:
    enabled: true

ootbingo:
  jobs:
    srl-sync:
      enabled: true
      cron: 0 0 0 * * ?
    racetime-sync:
      enabled: true
      cron: 0 0 1-23 * * ?

gg:
  racetime:
    api:
      data-base-url: https://racetime.gg
      racing-base-url: https://racetime.gg
      websocket-base-url: wss://racetime.gg

bingosync:
  base-url: https://bingosync.com

spring:
  datasource:
    url: jdbc:postgresql://scaramangado.de:10110/BARINADE
    driverClassName: org.postgresql.Driver
    username: scaramanga
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
