lily:
  commandline:
    enabled: false
  discord:
    enabled: true

ootbingo:
  jobs:
    srl-sync:
      enabled: true
      cron: 0 0 0 * * ?
    racetime-sync:
      enabled: true
      cron: 0 0 1-23 * * ?
    racetime-username-update:
      enabled: true
      cron: 0 30 1 * * ?

gg:
  racetime:
    api:
      data-base-url: https://racetime.gg
      racing-base-url: https://racetime.gg
      websocket-base-url: wss://racetime.gg

bingosync:
  base-url: https://bingosync.com

logging:
  file:
    name: bot.log
  logback:
    rollingpolicy:
      max-history: 30
      file-name-pattern: bot-%d{yyyy-MM-dd}.%i.log
      clean-history-on-start: true
  pattern:
    file: '%d{ISO8601} - %5p --- [%18.18t] %-40.40logger{39}:%-4.4L : %m%n'
    console:

spring:
  datasource:
    url: jdbc:postgresql://scaramangado.de:10110/BARINADE
    driverClassName: org.postgresql.Driver
    username: scaramanga
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
