name: Build Barinade Bot

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.BARINADE_SSH_KEY }}
      - name: Prepare
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Java Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: burrunan/gradle-cache-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          arguments: test
          gradle-version: wrapper
          properties: |
            githubPackagesUser=${{ secrets.PACKAGE_USER }}
            githubPackagesToken=${{ secrets.PACKAGE_PWD }}
      - name: SonarQube
        uses: burrunan/gradle-cache-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: sonarqube -x test
          gradle-version: wrapper
          properties: |
            githubPackagesUser=${{ secrets.PACKAGE_USER }}
            githubPackagesToken=${{ secrets.PACKAGE_PWD }}
            sonarUsername=${{ secrets.SONAR_USER }}
            sonarPassword=${{ secrets.SONAR_TOKEN }}
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build -x test
          gradle-version: wrapper
          properties: |
            githubPackagesUser=${{ secrets.PACKAGE_USER }}
            githubPackagesToken=${{ secrets.PACKAGE_PWD }}
      - name: Docker
        if: ${{ github.event_name == 'push' }}
        run: ./push-container.sh ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        run: |
          ssh -oStrictHostKeyChecking=no barinade@scaramangado.de /barinade/barinade-infrastructure/deploy.sh ${{ secrets.PACKAGE_USER }} ${{ secrets.PACKAGE_PWD}} ${GITHUB_REF#refs/heads/}
      - name: Notify (Success)
        uses: appleboy/discord-action@master
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feature/gh-actions' }}
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args: Build of ${GITHUB_REF#refs/heads/} successful
          color: #00ff00

