name: Build Barinade Bot

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.BARINADE_SSH_KEY }}
      - name: Save Branch Name
        id: branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF/refs\/heads\//}
      - name: Prepare
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Java Setup
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Test
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test
          gradle-version: wrapper
          properties: |
            githubPackagesUser=${{ secrets.PACKAGE_USER }}
            githubPackagesToken=${{ secrets.PACKAGE_PWD }}
      - name: SonarQube
        uses: burrunan/gradle-cache-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: sonar -x test
          gradle-version: wrapper
          properties: |
            githubPackagesUser=${{ secrets.PACKAGE_USER }}
            githubPackagesToken=${{ secrets.PACKAGE_PWD }}
            sonarUsername=${{ secrets.SONAR_USER }}
            sonarPassword=${{ secrets.SONAR_TOKEN }}
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build -x test
          gradle-version: wrapper
          properties: |
            githubPackagesUser=${{ secrets.PACKAGE_USER }}
            githubPackagesToken=${{ secrets.PACKAGE_PWD }}
      - name: Docker
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        run: ./push-container.sh ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          ssh -oStrictHostKeyChecking=no barinade@scaramangado.de /barinade/barinade-infrastructure/deploy.sh ${{ secrets.PACKAGE_USER }} ${{ secrets.PACKAGE_PWD}} ${GITHUB_REF#refs/heads/}
      - name: Notify (Success)
        uses: appleboy/discord-action@master
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: Build of ${{ steps.branch.outputs.BRANCH }} successful
          color: "#00ff00"
      - name: Notify (Fail)
        uses: appleboy/discord-action@master
        if: ${{ failure() }}
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: Build of ${{ steps.branch.outputs.BRANCH }} failed
          color: "#ff0000"
