name: Build Barinade Bot

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: actions/checkout@v2
      - name: Java Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test
          gradle-version: wrapper
          properties: |
            githubPackageUser=${{ secrets.PACKAGE_USER }}
            githubPackageToken=${{ secrets.PACKAGE_PWD }}
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build -x check
          gradle-version: wrapper
          properties: |
            githubPackageUser=${{ secrets.PACKAGE_USER }}
            githubPackageToken=${{ secrets.PACKAGE_PWD }}

